In [2]:
import pandas as pd

books = pd.read_csv("books_with_categories.csv")

In [3]:
from dotenv import load_dotenv

load_dotenv()

True

In [4]:
from transformers import pipeline
classifier = pipeline("text-classification", model="minuva/MiniLMv2-goemotions-v2", top_k=None, device=0)
classifier("I love this!")

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

[[{'label': 'love', 'score': 0.9897422790527344},
  {'label': 'admiration', 'score': 0.06898897141218185},
  {'label': 'joy', 'score': 0.033141590654850006},
  {'label': 'approval', 'score': 0.013628877699375153},
  {'label': 'gratitude', 'score': 0.009409158490598202},
  {'label': 'excitement', 'score': 0.008561301045119762},
  {'label': 'realization', 'score': 0.007664554286748171},
  {'label': 'disapproval', 'score': 0.007226626388728619},
  {'label': 'optimism', 'score': 0.007071783300489187},
  {'label': 'neutral', 'score': 0.006561584305018187},
  {'label': 'amusement', 'score': 0.0060904487036168575},
  {'label': 'caring', 'score': 0.0053924317471683025},
  {'label': 'annoyance', 'score': 0.004587485920637846},
  {'label': 'surprise', 'score': 0.00445652985945344},
  {'label': 'disappointment', 'score': 0.004451389890164137},
  {'label': 'desire', 'score': 0.003753138240426779},
  {'label': 'anger', 'score': 0.0037135579623281956},
  {'label': 'sadness', 'score': 0.0027831923216581345},
  {'label': 'confusion', 'score': 0.002500955481082201},
  {'label': 'curiosity', 'score': 0.0023105235304683447},
  {'label': 'disgust', 'score': 0.0019982715602964163},
  {'label': 'embarrassment', 'score': 0.0017060587415471673},
  {'label': 'relief', 'score': 0.0015821227570995688},
  {'label': 'fear', 'score': 0.0013966085389256477},
  {'label': 'remorse', 'score': 0.001355326152406633},
  {'label': 'pride', 'score': 0.0010492525761947036},
  {'label': 'nervousness', 'score': 0.0009846246102824807},
  {'label': 'grief', 'score': 0.0009114280692301691}]]

In [5]:
books["description"][0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.'

In [6]:
classifier(books["description"][0])

[[{'label': 'neutral', 'score': 0.8618752956390381},
  {'label': 'admiration', 'score': 0.19000545144081116},
  {'label': 'approval', 'score': 0.02519521303474903},
  {'label': 'realization', 'score': 0.014012510888278484},
  {'label': 'caring', 'score': 0.007002498488873243},
  {'label': 'pride', 'score': 0.006460831966251135},
  {'label': 'annoyance', 'score': 0.006445091217756271},
  {'label': 'disappointment', 'score': 0.0054513015784323215},
  {'label': 'optimism', 'score': 0.004780944902449846},
  {'label': 'excitement', 'score': 0.00460670655593276},
  {'label': 'sadness', 'score': 0.003549613757058978},
  {'label': 'fear', 'score': 0.002757053356617689},
  {'label': 'anger', 'score': 0.0026885236147791147},
  {'label': 'relief', 'score': 0.0021370812319219112},
  {'label': 'joy', 'score': 0.002048950642347336},
  {'label': 'surprise', 'score': 0.0018958442378789186},
  {'label': 'nervousness', 'score': 0.001618034322746098},
  {'label': 'desire', 'score': 0.0014834475005045533},
  {'label': 'disapproval', 'score': 0.0014209117507562041},
  {'label': 'remorse', 'score': 0.0012592088896781206},
  {'label': 'grief', 'score': 0.0012149844551458955},
  {'label': 'embarrassment', 'score': 0.0011849056463688612},
  {'label': 'disgust', 'score': 0.0010419918689876795},
  {'label': 'confusion', 'score': 0.0010295371757820249},
  {'label': 'gratitude', 'score': 0.0010272333165630698},
  {'label': 'amusement', 'score': 0.0008916083024814725},
  {'label': 'curiosity', 'score': 0.0008428330183960497},
  {'label': 'love', 'score': 0.0006087215733714402}]]

In [ ]:
classifier(books["description"][0].split("."))

In [8]:
sentences = books["description"][0].split(".")
predictions = classifier(sentences)

In [9]:
sentences[0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives'

In [10]:
predictions[0]

[{'label': 'excitement', 'score': 0.6809415221214294},
 {'label': 'admiration', 'score': 0.5272738933563232},
 {'label': 'surprise', 'score': 0.11731090396642685},
 {'label': 'curiosity', 'score': 0.08301174640655518},
 {'label': 'annoyance', 'score': 0.026338467374444008},
 {'label': 'anger', 'score': 0.025204328820109367},
 {'label': 'fear', 'score': 0.019735921174287796},
 {'label': 'neutral', 'score': 0.01909146085381508},
 {'label': 'disappointment', 'score': 0.0123396972194314},
 {'label': 'approval', 'score': 0.01121499016880989},
 {'label': 'desire', 'score': 0.011024005711078644},
 {'label': 'joy', 'score': 0.010932660661637783},
 {'label': 'amusement', 'score': 0.009570172056555748},
 {'label': 'realization', 'score': 0.009564786218106747},
 {'label': 'optimism', 'score': 0.005885463673621416},
 {'label': 'confusion', 'score': 0.005844053812325001},
 {'label': 'disapproval', 'score': 0.005843530874699354},
 {'label': 'pride', 'score': 0.00538467476144433},
 {'label': 'sadness', 'score': 0.00471515953540802},
 {'label': 'nervousness', 'score': 0.003867033403366804},
 {'label': 'caring', 'score': 0.0022309368941932917},
 {'label': 'gratitude', 'score': 0.002169010229408741},
 {'label': 'embarrassment', 'score': 0.0021424121223390102},
 {'label': 'disgust', 'score': 0.0021240694914013147},
 {'label': 'love', 'score': 0.002092556329444051},
 {'label': 'remorse', 'score': 0.0020765510853379965},
 {'label': 'grief', 'score': 0.0018844751175493002},
 {'label': 'relief', 'score': 0.0007647298043593764}]

In [11]:
sentences[3]

' Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist'

In [12]:
predictions[3]

[{'label': 'neutral', 'score': 0.9553009271621704},
 {'label': 'annoyance', 'score': 0.01768709532916546},
 {'label': 'anger', 'score': 0.011694921180605888},
 {'label': 'fear', 'score': 0.011625528335571289},
 {'label': 'realization', 'score': 0.010278478264808655},
 {'label': 'admiration', 'score': 0.009243941865861416},
 {'label': 'approval', 'score': 0.007315267808735371},
 {'label': 'caring', 'score': 0.005755335558205843},
 {'label': 'disappointment', 'score': 0.005260900128632784},
 {'label': 'sadness', 'score': 0.003802703693509102},
 {'label': 'optimism', 'score': 0.003273645183071494},
 {'label': 'pride', 'score': 0.0024441820569336414},
 {'label': 'surprise', 'score': 0.002401749137789011},
 {'label': 'nervousness', 'score': 0.002329232171177864},
 {'label': 'confusion', 'score': 0.0020497094374150038},
 {'label': 'disapproval', 'score': 0.0020034275949001312},
 {'label': 'excitement', 'score': 0.0017463030526414514},
 {'label': 'disgust', 'score': 0.001675400766544044},
 {'label': 'embarrassment', 'score': 0.0015153741696849465},
 {'label': 'amusement', 'score': 0.0013351845555007458},
 {'label': 'relief', 'score': 0.0013083808589726686},
 {'label': 'curiosity', 'score': 0.001173290191218257},
 {'label': 'grief', 'score': 0.0010819801827892661},
 {'label': 'remorse', 'score': 0.0010679266415536404},
 {'label': 'desire', 'score': 0.0009717599023133516},
 {'label': 'joy', 'score': 0.000777735433075577},
 {'label': 'love', 'score': 0.0005221429746598005},
 {'label': 'gratitude', 'score': 0.00037128260009922087}]

In [13]:
sorted(predictions[0], key=lambda x: x["label"])

[{'label': 'admiration', 'score': 0.5272738933563232},
 {'label': 'amusement', 'score': 0.009570172056555748},
 {'label': 'anger', 'score': 0.025204328820109367},
 {'label': 'annoyance', 'score': 0.026338467374444008},
 {'label': 'approval', 'score': 0.01121499016880989},
 {'label': 'caring', 'score': 0.0022309368941932917},
 {'label': 'confusion', 'score': 0.005844053812325001},
 {'label': 'curiosity', 'score': 0.08301174640655518},
 {'label': 'desire', 'score': 0.011024005711078644},
 {'label': 'disappointment', 'score': 0.0123396972194314},
 {'label': 'disapproval', 'score': 0.005843530874699354},
 {'label': 'disgust', 'score': 0.0021240694914013147},
 {'label': 'embarrassment', 'score': 0.0021424121223390102},
 {'label': 'excitement', 'score': 0.6809415221214294},
 {'label': 'fear', 'score': 0.019735921174287796},
 {'label': 'gratitude', 'score': 0.002169010229408741},
 {'label': 'grief', 'score': 0.0018844751175493002},
 {'label': 'joy', 'score': 0.010932660661637783},
 {'label': 'love', 'score': 0.002092556329444051},
 {'label': 'nervousness', 'score': 0.003867033403366804},
 {'label': 'neutral', 'score': 0.01909146085381508},
 {'label': 'optimism', 'score': 0.005885463673621416},
 {'label': 'pride', 'score': 0.00538467476144433},
 {'label': 'realization', 'score': 0.009564786218106747},
 {'label': 'relief', 'score': 0.0007647298043593764},
 {'label': 'remorse', 'score': 0.0020765510853379965},
 {'label': 'sadness', 'score': 0.00471515953540802},
 {'label': 'surprise', 'score': 0.11731090396642685}]

In [16]:
import numpy as np

emotion_labels = [
    'admiration', 'amusement', 'anger', 'annoyance', 'approval', 'caring',
    'confusion', 'curiosity', 'desire', 'disappointment', 'disapproval',
    'disgust', 'embarrassment', 'excitement', 'fear', 'gratitude', 'grief',
    'joy', 'love', 'nervousness', 'neutral', 'optimism', 'pride',
    'realization', 'relief', 'remorse', 'sadness', 'surprise'
]

isbn = []
emotion_scores = {label: [] for label in emotion_labels}

def calculate_max_emotion_scores(predictions):
    per_emotion_scores = {label: [] for label in emotion_labels}
    for prediction in predictions:
        sorted_predictions = sorted(prediction, key=lambda x: x["label"])
        for index, label in enumerate(emotion_labels):
            per_emotion_scores[label].append(sorted_predictions[index]["score"])
    return {label: np.max(scores) for label, scores in per_emotion_scores.items()}

In [18]:
for i in range(10):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores  = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

In [19]:
emotion_scores

{'admiration': [np.float64(0.8905187249183655),
  np.float64(0.9804762601852417),
  np.float64(0.989074170589447),
  np.float64(0.04773283377289772),
  np.float64(0.883320689201355),
  np.float64(0.01719852164387703),
  np.float64(0.9777058959007263),
  np.float64(0.9405513405799866),
  np.float64(0.0757509246468544),
  np.float64(0.006495540030300617)],
 'amusement': [np.float64(0.020829016342759132),
  np.float64(0.18023787438869476),
  np.float64(0.005994749721139669),
  np.float64(0.002199001843109727),
  np.float64(0.0019114946480840445),
  np.float64(0.0029053587932139635),
  np.float64(0.002570646582171321),
  np.float64(0.003498529549688101),
  np.float64(0.0020600538700819016),
  np.float64(0.0016286240424960852)],
 'anger': [np.float64(0.025204328820109367),
  np.float64(0.005729698110371828),
  np.float64(0.04011368378996849),
  np.float64(0.00446272874251008),
  np.float64(0.0025546872057020664),
  np.float64(0.014398384839296341),
  np.float64(0.004458241164684296),
  np.float64(0.005219791550189257),
  np.float64(0.0025468342937529087),
  np.float64(0.0013787499628961086)],
 'annoyance': [np.float64(0.026338467374444008),
  np.float64(0.01198110356926918),
  np.float64(0.03559105470776558),
  np.float64(0.006065347231924534),
  np.float64(0.007576294243335724),
  np.float64(0.087855763733387),
  np.float64(0.016045203432440758),
  np.float64(0.014465583488345146),
  np.float64(0.009469625540077686),
  np.float64(0.004410312045365572)],
 'approval': [np.float64(0.149612158536911),
  np.float64(0.48477911949157715),
  np.float64(0.038392458111047745),
  np.float64(0.09656088054180145),
  np.float64(0.36061060428619385),
  np.float64(0.03277318552136421),
  np.float64(0.09843543916940689),
  np.float64(0.029934419319033623),
  np.float64(0.018129626289010048),
  np.float64(0.028462931513786316)],
 'caring': [np.float64(0.11520551890134811),
  np.float64(0.002606708789244294),
  np.float64(0.0089619942009449),
  np.float64(0.009603019803762436),
  np.float64(0.21014592051506042),
  np.float64(0.002562732668593526),
  np.float64(0.0056225149892270565),
  np.float64(0.0036670274566859007),
  np.float64(0.0010809792438521981),
  np.float64(0.0007311374647542834)],
 'confusion': [np.float64(0.005844053812325001),
  np.float64(0.4023124873638153),
  np.float64(0.021610377356410027),
  np.float64(0.0029112559277564287),
  np.float64(0.043386414647102356),
  np.float64(0.003413732396438718),
  np.float64(0.15707457065582275),
  np.float64(0.028796225786209106),
  np.float64(0.02132185734808445),
  np.float64(0.001387484953738749)],
 'curiosity': [np.float64(0.08301174640655518),
  np.float64(0.48346489667892456),
  np.float64(0.0185298640280962),
  np.float64(0.0010658141691237688),
  np.float64(0.48309364914894104),
  np.float64(0.0012379686813801527),
  np.float64(0.050639327615499496),
  np.float64(0.001552798319607973),
  np.float64(0.44511666893959045),
  np.float64(0.0009950578678399324)],
 'desire': [np.float64(0.011024005711078644),
  np.float64(0.005440144333988428),
  np.float64(0.013082556426525116),
  np.float64(0.0035408898256719112),
  np.float64(0.018131056800484657),
  np.float64(0.0010047259274870157),
  np.float64(0.2774568498134613),
  np.float64(0.002188564045354724),
  np.float64(0.0008019988308660686),
  np.float64(0.0005527510074898601)],
 'disappointment': [np.float64(0.10653550177812576),
  np.float64(0.018031593412160873),
  np.float64(0.012942219153046608),
  np.float64(0.0062753865495324135),
  np.float64(0.005593332462012768),
  np.float64(0.4763803482055664),
  np.float64(0.03687543049454689),
  np.float64(0.01214828621596098),
  np.float64(0.0138281574472785),
  np.float64(0.0014348841505125165)],
 'disapproval': [np.float64(0.0060029411688447),
  np.float64(0.003463209606707096),
  np.float64(0.008637565188109875),
  np.float64(0.011890597641468048),
  np.float64(0.004553011618554592),
  np.float64(0.043030064553022385),
  np.float64(0.6107532978057861),
  np.float64(0.010271637700498104),
  np.float64(0.007975421845912933),
  np.float64(0.0010990048758685589)],
 'disgust': [np.float64(0.004366254433989525),
  np.float64(0.0012118943268433213),
  np.float64(0.006063154898583889),
  np.float64(0.003104808274656534),
  np.float64(0.0024378423113375902),
  np.float64(0.022610927000641823),
  np.float64(0.004687109496444464),
  np.float64(0.002849676413461566),
  np.float64(0.002779910806566477),
  np.float64(0.0008747797692194581)],
 'embarrassment': [np.float64(0.003630217630416155),
  np.float64(0.0017284202622249722),
  np.float64(0.003930800594389439),
  np.float64(0.003423027228564024),
  np.float64(0.0013173549668863416),
  np.float64(0.02379400096833706),
  np.float64(0.002060122322291136),
  np.float64(0.0017027112189680338),
  np.float64(0.0019374275580048561),
  np.float64(0.0005227514775469899)],
 'excitement': [np.float64(0.6809415221214294),
  np.float64(0.01530767697840929),
  np.float64(0.02530600130558014),
  np.float64(0.006141758058220148),
  np.float64(0.004862816073000431),
  np.float64(0.0026746883522719145),
  np.float64(0.004058776888996363),
  np.float64(0.033323023468256),
  np.float64(0.0030466094613075256),
  np.float64(0.0018587240483611822)],
 'fear': [np.float64(0.019735921174287796),
  np.float64(0.0031655775383114815),
  np.float64(0.9347721338272095),
  np.float64(0.0067784967832267284),
  np.float64(0.005964774172753096),
  np.float64(0.00268761464394629),
  np.float64(0.11571905016899109),
  np.float64(0.014942712150514126),
  np.float64(0.0021859018597751856),
  np.float64(0.00035382408532314)],
 'gratitude': [np.float64(0.01577582210302353),
  np.float64(0.008887650445103645),
  np.float64(0.007416780572384596),
  np.float64(0.0014582276344299316),
  np.float64(0.009220363572239876),
  np.float64(0.0022081146016716957),
  np.float64(0.019849978387355804),
  np.float64(0.0018658698536455631),
  np.float64(0.0009319347445853055),
  np.float64(0.000584432331379503)],
 'grief': [np.float64(0.01543246116489172),
  np.float64(0.0008811487932689488),
  np.float64(0.0038153878413140774),
  np.float64(0.0012152820127084851),
  np.float64(0.001991159748286009),
  np.float64(0.007163195870816708),
  np.float64(0.0031398599967360497),
  np.float64(0.0012201257050037384),
  np.float64(0.0015952673275023699),
  np.float64(0.0003855192626360804)],
 'joy': [np.float64(0.9135670065879822),
  np.float64(0.01755734719336033),
  np.float64(0.007901935838162899),
  np.float64(0.009047471918165684),
  np.float64(0.0038276533596217632),
  np.float64(0.003916712943464518),
  np.float64(0.0036415099166333675),
  np.float64(0.1344076246023178),
  np.float64(0.001769660273566842),
  np.float64(0.0018614135915413499)],
 'love': [np.float64(0.0034766921307891607),
  np.float64(0.002173246815800667),
  np.float64(0.26191776990890503),
  np.float64(0.9647554159164429),
  np.float64(0.004292671103030443),
  np.float64(0.0008311273413710296),
  np.float64(0.002164937788620591),
  np.float64(0.002696065930649638),
  np.float64(0.0028360101860016584),
  np.float64(0.0005121665890328586)],
 'nervousness': [np.float64(0.008674132637679577),
  np.float64(0.003839103039354086),
  np.float64(0.10204795747995377),
  np.float64(0.003378694411367178),
  np.float64(0.0026757519226521254),
  np.float64(0.003062238683924079),
  np.float64(0.01902778260409832),
  np.float64(0.0020074662752449512),
  np.float64(0.0015399884432554245),
  np.float64(0.00031837113783694804)],
 'neutral': [np.float64(0.9881018400192261),
  np.float64(0.9889149069786072),
  np.float64(0.9881018400192261),
  np.float64(0.9881018400192261),
  np.float64(0.9911152124404907),
  np.float64(0.9881018400192261),
  np.float64(0.9881018400192261),
  np.float64(0.9881018400192261),
  np.float64(0.9881018400192261),
  np.float64(0.9881018400192261)],
 'optimism': [np.float64(0.015898803249001503),
  np.float64(0.01728133112192154),
  np.float64(0.01795472949743271),
  np.float64(0.006354197859764099),
  np.float64(0.2078949511051178),
  np.float64(0.0029189966153353453),
  np.float64(0.7781580090522766),
  np.float64(0.003999721258878708),
  np.float64(0.0024417834356427193),
  np.float64(0.0013228340540081263)],
 'pride': [np.float64(0.054634954780340195),
  np.float64(0.004025921691209078),
  np.float64(0.005543320439755917),
  np.float64(0.0016266374150291085),
  np.float64(0.0038709223736077547),
  np.float64(0.0021791011095046997),
  np.float64(0.007035673595964909),
  np.float64(0.004685910418629646),
  np.float64(0.0017153769731521606),
  np.float64(0.001089878031052649)],
 'realization': [np.float64(0.03384463116526604),
  np.float64(0.07924503087997437),
  np.float64(0.03539905324578285),
  np.float64(0.03180137649178505),
  np.float64(0.02590516209602356),
  np.float64(0.7527893781661987),
  np.float64(0.08795050531625748),
  np.float64(0.014194520190358162),
  np.float64(0.02748809941112995),
  np.float64(0.008648731745779514)],
 'relief': [np.float64(0.04834119603037834),
  np.float64(0.001079121488146484),
  np.float64(0.004276052117347717),
  np.float64(0.0022364864125847816),
  np.float64(0.003999575041234493),
  np.float64(0.0019862111657857895),
  np.float64(0.0024169408716261387),
  np.float64(0.002766503719612956),
  np.float64(0.0011706064688041806),
  np.float64(0.0005905995494686067)],
 'remorse': [np.float64(0.008523317985236645),
  np.float64(0.0010314028477296233),
  np.float64(0.0031301320996135473),
  np.float64(0.0012036877451464534),
  np.float64(0.0042821369133889675),
  np.float64(0.013308706693351269),
  np.float64(0.0036063671577721834),
  np.float64(0.002323341555893421),
  np.float64(0.001597999013029039),
  np.float64(0.0004030200943816453)],
 'sadness': [np.float64(0.6211659908294678),
  np.float64(0.005160235334187746),
  np.float64(0.016237972304224968),
  np.float64(0.0035594734363257885),
  np.float64(0.007245635613799095),
  np.float64(0.33609047532081604),
  np.float64(0.03408130258321762),
  np.float64(0.005481965374201536),
  np.float64(0.012507189996540546),
  np.float64(0.0009667777339927852)],
 'surprise': [np.float64(0.11731090396642685),
  np.float64(0.014360715635120869),
  np.float64(0.008307681418955326),
  np.float64(0.004030492622405291),
  np.float64(0.003380282549187541),
  np.float64(0.011738520115613937),
  np.float64(0.006302942521870136),
  np.float64(0.0036583850160241127),
  np.float64(0.16690753400325775),
  np.float64(0.0012016820255666971)]}

In [20]:
from tqdm import tqdm

emotion_labels = [
    'admiration', 'amusement', 'anger', 'annoyance', 'approval', 'caring',
    'confusion', 'curiosity', 'desire', 'disappointment', 'disapproval',
    'disgust', 'embarrassment', 'excitement', 'fear', 'gratitude', 'grief',
    'joy', 'love', 'nervousness', 'neutral', 'optimism', 'pride',
    'realization', 'relief', 'remorse', 'sadness', 'surprise'
]

isbn = []
emotion_scores = {label: [] for label in emotion_labels}

for i in tqdm(range(len(books))):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores  = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

100%|██████████| 5197/5197 [06:34<00:00, 13.18it/s]

In [21]:
emotions_df = pd.DataFrame(emotion_scores)
emotions_df["isbn13"] = isbn
# %%
emotions_df.to_csv("emotions.csv", index=False)

In [22]:
emotions_df.head()

,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,desire,disappointment,...,nervousness,neutral,optimism,pride,realization,relief,remorse,sadness,surprise,isbn13
0,0.890519,0.020829,0.025204,0.026338,0.149612,0.115206,0.005844,0.083012,0.011024,0.106536,...,0.008674,0.988102,0.015899,0.054635,0.033845,0.048341,0.008523,0.621166,0.117311,9780002005883
1,0.980476,0.180238,0.005730,0.011981,0.484779,0.002607,0.402312,0.483465,0.005440,0.018032,...,0.003839,0.988915,0.017281,0.004026,0.079245,0.001079,0.001031,0.005160,0.014361,9780002261982
2,0.989074,0.005995,0.040114,0.035591,0.038392,0.008962,0.021610,0.018530,0.013083,0.012942,...,0.102048,0.988102,0.017955,0.005543,0.035399,0.004276,0.003130,0.016238,0.008308,9780006178736
3,0.047733,0.002199,0.004463,0.006065,0.096561,0.009603,0.002911,0.001066,0.003541,0.006275,...,0.003379,0.988102,0.006354,0.001627,0.031801,0.002236,0.001204,0.003559,0.004030,9780006280897
4,0.883321,0.001911,0.002555,0.007576,0.360611,0.210146,0.043386,0.483094,0.018131,0.005593,...,0.002676,0.991115,0.207895,0.003871,0.025905,0.004000,0.004282,0.007246,0.003380,9780006280934

In [23]:
books = pd.merge(books, emotions_df, on="isbn13")

In [24]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,...,love,nervousness,neutral,optimism,pride,realization,relief,remorse,sadness,surprise
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,...,0.003477,0.008674,0.988102,0.015899,0.054635,0.033845,0.048341,0.008523,0.621166,0.117311
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,0.002173,0.003839,0.988915,0.017281,0.004026,0.079245,0.001079,0.001031,0.005160,0.014361
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,...,0.261918,0.102048,0.988102,0.017955,0.005543,0.035399,0.004276,0.003130,0.016238,0.008308
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,...,0.964755,0.003379,0.988102,0.006354,0.001627,0.031801,0.002236,0.001204,0.003559,0.004030
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,...,0.004293,0.002676,0.991115,0.207895,0.003871,0.025905,0.004000,0.004282,0.007246,0.003380
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,...,0.818229,0.004609,0.983566,0.004212,0.007880,0.185607,0.002624,0.003279,0.105872,0.041430
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,...,0.002609,0.000571,0.988102,0.007563,0.004297,0.275989,0.001457,0.001153,0.001792,0.003743
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,...,0.003631,0.002101,0.282214,0.061856,0.014068,0.029030,0.021355,0.002089,0.006890,0.002193
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,...,0.003935,0.012204,0.988102,0.010160,0.011714,0.095255,0.005563,0.007821,0.225562,0.002273
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,...,0.004430,0.001189,0.988102,0.980478,0.007248,0.138055,0.004255,0.002720,0.002455,0.003190

In [25]:
books.to_csv("books_with_emotions.csv", index=False)